"""empty message

Revision ID: 22f9f36d748c
Revises: 
Create Date: 2023-04-17 16:22:29.894119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f9f36d748c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('PhoneNumbers',
    sa.Column('phone_num_id', sa.Integer(), nullable=False),
    sa.Column('phone_num', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('phone_num_id')
    )
    op.create_table('Models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['Brands.brand_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('Profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('total_searched_cars', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('phone_num_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_num_id'], ['PhoneNumbers.phone_num_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['Profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Profiles')
    op.drop_table('Models')
    op.drop_table('PhoneNumbers')
    op.drop_table('Brands')
    # ### end Alembic commands ###
