"""Initial migration

Revision ID: 584ee74476d3
Revises: 
Create Date: 2023-04-03 14:01:03.877073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "584ee74476d3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PhoneNumbers",
        sa.Column("phone_num_id", sa.Integer(), nullable=False),
        sa.Column("phone_num", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("phone_num_id"),
    )
    op.create_table(
        "Profiles",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("total_searched_cars", sa.Integer(), nullable=False),
        sa.Column("registration_date", sa.DateTime(), nullable=False),
        sa.Column("phone_num_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phone_num_id"],
            ["PhoneNumbers.phone_num_id"],
        ),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["Profiles.profile_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Users")
    op.drop_table("Profiles")
    op.drop_table("PhoneNumbers")
    # ### end Alembic commands ###
