"""empty message

Revision ID: 84a33bb86895
Revises: 1c8d89d253c6
Create Date: 2023-04-04 15:22:53.892121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84a33bb86895"
down_revision = "1c8d89d253c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("surname", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.alter_column("surname", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
