"""empty message

Revision ID: 9ce2fea93f1b
Revises: 584ee74476d3
Create Date: 2023-04-03 14:37:19.962100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ce2fea93f1b"
down_revision = "584ee74476d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username", sa.String(length=100), nullable=False)
        )
        batch_op.add_column(
            sa.Column("password", sa.String(length=250), nullable=False)
        )
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("password")
        batch_op.drop_column("username")

    # ### end Alembic commands ###
